permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Fall
year: 2019
subtitle: Fall Comp 2019

num_years_crimson_existed: 146

monthly_page_views_millions: 1.3
yearly_page_views_millions: 15.1
yearly_page_time_spent_years: 58

google_doc_signup: https://forms.gle/1BAPt9ofAbXGv7B58
facebook_rsvp_link: https://www.facebook.com/events/447740999149311/

president: Kristine E. Guillaume
managing_editor: Angela N. Fu
business_manager: Charlie B. Zhu

arts:
  dir1:
    name: Liana E. Chow
    email: liana.chow@thecrimson.com
  dir2:
    name: Allison J. Scharmann
    email: allison.scharmann@thecrimson.com

blog:
  dir1:
    name: Claire J. Hoffman
    email: claire.hoffman@thecrimson.com
  dir2:
    name: Linda Lee
    email: linda.lee@thecrimson.com

business:
  dir1:
    name: Jonathan V. Garzon
    email: jonathan.garzon@thecrimson.com
  dir2:
    name: Joanne Lee
    email: joanne.lee@thecrimson.com

design:
  web:
    dir1:
      name: Hanna Kim
      email: hanna.kim@thecrimson.com
  illustration:
    dir1:
      name: Isabella C. Aslarus
      email: isabella.aslarus@thecrimson.com
  print:
    dir1:
      name: Truelian Lee
      email: truelian.lee@thecrimson.com

editorial:
  dir1:
    name: Romy Dolgin
    email: romy.dolgin@thecrimson.com
  dir2:
    name: Elijah T. Ezeji-Okoye
    email: elijah.ezeji-okoye@thecrimson.com

magazine:
  dir1:
    name: Andrew W.D. Aoyama
    email: andrew.aoyama@thecrimson.com
  dir2:
    name: Nina H. Pasquini
    email: nina.pasquini@thecrimson.com

news:
  dir1:
    name: Michael E. Xie
    email: michael.xie@thecrimson.com
  dir2:
    name: Luke W. Xu
    email: luke.xu@thecrimson.com

multimedia:
  dir1:
    name: Allison G. Lee
    email: allison.lee@thecrimson.com
  dir2:
    name: Amy Y. Li
    email: amy.li@thecrimson.com

sports:
  dir1:
    name: Amir Mamdani
    email: amir.mamdani@thecrimson.com
  dir2:
    name: Eamon J. McLoughlin
    email: eamon.mcloughlin@thecrimson.com

technology:
  dir1:
    name: Nicholas F. Wong
    email: nicholas.wong@thecrimson.com
  dir2:
    name: William Y. Yao
    email: william.yao@thecrimson.com
