permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Fall
year: 2018
subtitle: Fall Comp 2018

num_years_crimson_existed: 145

monthly_page_views_millions: 1.7
yearly_page_views_millions: 17.5
yearly_page_time_spent_years: 36

open_house: January 29 and 31, at 7 PM
google_doc_signup: https://goo.gl/forms/VZ5TjyqeyWBHRmDk2

president: Derek G. Xiao
managing_editor: Hannah Natanson
business_manager: Nathan Y. Lee

arts:
  dir1:
    name: Kaylee S. Kim
    email: kaylee.kim@thecrimson.com
  dir2:
    name: Caroline A. Tsai
    email: caroline.tsai@thecrimson.com

blog:
  dir1:
    name: Sophie G. Garrett
    email: sophie.garrett@thecrimson.com

business:
  dir1:
    name: Jack Yoon
    email: jack.yoon@thecrimson.com

  dir2:
    name: Charlie B. Zhu
    email: charlie.zhu@thecrimson.com

design:
  web:
    dir1:
      name: Akhil S. Waghmare
      email: akhil.waghmare@thecrimson.com
  illustration:
    dir1:
      name: Danukshi A. Mudannayake
      email: danukshi.mudannayake@thecrimson.com
    dir2:
      name: Maria H. Park
      email: maria.park@thecrimson.com

editorial:
  dir1:
    name: Elijah T. Ezeji-Okoye
    email: elijah.ezeji-okoye@thecrimson.com
  dir2:
    name: Shireen Younus
    email: shireen.younus@thecrimson.com

magazine:
  dir1:
    name: Norah M. Murphy
    email: norah.murphy@thecrimson.com
  dir2:
    name:  Drew C. Pendergrass
    email: drew.pendergrass@thecrimson.com

news:
  dir1:
    name: Joshua J. Florence
    email: joshua.florence@thecrimson.com
  dir2:
    name: Kenton K. Shimozaki
    email: kenton.shimozaki@thecrimson.com

multimedia:
  dir1:
    name: Iulianna Taritsa
    email: iulianna.taritsa@thecrimson.com

  dir2:
    name: Margaret Ross
    email: margaret.ross@thecrimson.com

sports:
  dir1:
    name: Kimberley Arango
    email: kim.arango@thecrimson.com

technology:
  dir1:
    name: Richard M. Wang
    email: richard.m.wang@thecrimson.com
  dir2:
    name: Nicholas F. Wong
    email: nicholas.wong@thecrimson.com
